// This file was generated by Prisma, and assumes you run Prisma commands using `bun --bun run prisma [command]`.
import { defineConfig } from "prisma/config";
import { Environment } from "./shared/config";

const env = new Environment;
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
      url: env.databaseUrl,
      shadowDatabaseUrl: env.databaseUrl.replace(/\/[^/]*\?/, "/tabledash_shadow?"),
    // url: env("DATABASE_URL"),
  },
});
