// This file was generated by Prisma, and assumes you run Prisma commands using `bun --bun run prisma [command]`.
import { defineConfig } from "prisma/config";
import { Environment } from "./shared/config";

const env = new Environment;
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // No shadowDatabaseUrl is configured on purpose: production DATABASE_URLs
    // (e.g. postgres://…/railway) often lack a query string, and the previous
    // regex-based derivation produced a shadow URL identical to the main one,
    // which made `prisma migrate deploy` fail at boot. Prisma auto-creates a
    // shadow database for local `migrate dev` when none is provided.
    url: env.databaseUrl,
  },
});
